### ISSUE TITLE
System reports the build was signed with public keys

### ISSUE THREAD

**Issue by blackshibe** [lineageos-on-pdx201/releases#1]
![image](https://github.com/lineageos-on-pdx201/releases/assets/57596776/15eccfdb-5ff7-4d75-99e1-18f91a0836d1)

^ test-keys are being used with [this release](https://github.com/lineageos-on-pdx201/releases/releases/tag/20.0-20230615-UNOFFICIAL)

**Comment by Mashopy** [comment]
This is an expected behavior for unofficial builds in LineageOS, only official one are signed and I do not intend to sign them myself as this will bring more problems for current users to switch to official builds when they will be available
