### ISSUE TITLE
Audio stutters during load

### ISSUE THREAD

**Issue by blackshibe** [lineageos-on-pdx201/releases#2]
I haven't noticed this on other ROMs or with a LineageOS 19.1 build I compiled from 20230331 so I assume it's a bug.

Notifications & music playback will stutter If I receive a notification meanwhile. I noticed this the most while watching Youtube and getting a notification on Discord/Signal.

The easiest repro is playing a video and changing volume simultaneously. I don't know if It's the same bug though.

Example: https://youtube.com/shorts/Lr-wM5bNkQE

**Comment by Mashopy** [comment]
I'm unable to reproduce that bug with the latest audio related changes that I've pushed recently, so I guess I fixed it at some point. However, this issue will remain open until this is confirmed to be fixed with the next release that might come this week.

**Comment by blackshibe** [comment]
Testing with 20230629:

https://youtube.com/shorts/EfkY4jWPqg4

Only appears on the 5-6 highest volume levels
Doesn't happen with bluetooth connected

Logcat segment:

[logcat.log](https://github.com/lineageos-on-pdx201/releases/files/11901486/logcat.log)

**Comment by Mashopy** [comment]
Did u took every patches present on this org and on LineageOS Gerrit before building ?

**Comment by blackshibe** [comment]
I redownloaded the source from scratch because of unrelated reasons so I assume it's up to date. If it makes any difference I can tell the dual-mono patch is applied

I'll also try a factory reset with the next release you mentioned when it's released

**Comment by blackshibe** [comment]
It happens in safe mode too, but only after some time has passed since reboot

To reproduce I reboot the phone & wait 10-30 minutes then start playing audio

**Comment by blackshibe** [comment]
Doesn't happen with latest commits anymore. There's also no stutter when getting notifications or alarms.
