### ISSUE TITLE
"Serial Console Enabled" message

### ISSUE THREAD

**Issue by savegame** [lineageos-on-pdx201/releases#3]
Its always show this message, how to disable it? 

`Serial console Enabled. Performance is impacted. To disable check bootloader.`
installed from Releases

**Comment by savegame** [comment]
maybe you can tell me how to rebuild kernel without serial console support? (with maximum performance)

**Comment by Mashopy** [comment]
Serial console doesn't affect performance at all, that's just a warning to not keep it enabled for no reason. I will disable it for the next release.

**Comment by savegame** [comment]
Thanks. when you planning new release? =)

**Comment by Mashopy** [comment]
Fixed on kernel side since a while, fix will be included on new release whenever I decide to release it
